# These are supported funding model platforms

github: # KABUKAL e.lace g., [KABUKAL1, KABUKAL]
patreon: # KABUKAL
open_collective: # KABUKAL
ko_fi: # KABUKAL
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # KABUKAL
issuehunt: # KABUKAL
otechie: # KABUKAL
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https:/// wwwkabukal.go.id', 'https:/// kabukal.go.id']
